### ISSUE TITLE
Test coverage percentage

### ISSUE THREAD

**Issue by tomwilding** [mulesoft/munit#156] opened 2015-02-12 08:35 UTC
I am testing a flow with three components, all wrapped within an asynchronous scope. The test runs successfully and all three elements (including the asynchronous scope) are marked with green ticks, however the test coverage reports 68% (the test does not test anything other than this). My problem is why the coverage reported is not 100% as all message processors are ticked? Could it be the asynchronous scope?

**Comment by tomwilding** [comment] 2015-02-12 11:41
Hi, turns out this is nothing to do with the asynchronous scope because I still get the issue when taking it out. I just created a little git project with my problem... wonder if anyone can help me!
https://github.com/tomwilding/MunitCoverageTest

**Comment by tomwilding** [comment] 2015-02-12 11:43
There is just one test suite with two test cases. Running the tests ticks all message processors (exploring all flow routes) however the test coverage is only 60%. I would expect 100% coverage, the only thing I can think is that exceptions are not covered. Any ideas?

**Comment by tomwilding** [comment] 2015-02-12 13:38
![screen shot 2015-02-12 at 13 37 01](https://cloud.githubusercontent.com/assets/2557535/6168336/644a3da0-b2bc-11e4-9e14-7997a0712524.png)

**Comment by tomwilding** [comment] 2015-02-12 13:38
As you can see, the elements are all checked with green ticks but the coverage is 60.00%

**Comment by damiansima** [comment] 2015-02-17 15:51
Hi @tomwilding 

Thanks for reporting I'll take a look at it and get back to you ;)

**Comment by tomwilding** [comment] 2015-03-02 09:26
@damiansima any luck?

**Comment by damiansima** [comment] 2015-03-03 19:10
Hi @tomwilding 

Sorry for the delay, lot's of busy days. 

So I gave it a quick look and it looks like a bug in the way we count the MP in the coverage module.
I don't think this will be fixed this week but it's certainly on my radar and I'll try to fix this as soon as I finish some other stuff. 

Thanks a lot for you patience, Cheers!

**Comment by damiansima** [comment] 2015-03-11 14:21
Hi @tomwilding, 

I fixed the coverage issue. It will be there in one of the next releases of the Anypoint Studio plugin.
To give you a little bit of context, it was caused by the way the choice router processor chain (that is the chain of MPs inside the choice) is composed and created. Which was causing an error in the count of total MP and the ones the application went through. 

Here you can see a few screenshots: 
![screen shot 2015-03-11 at 11 20 12 am](https://cloud.githubusercontent.com/assets/1579786/6598192/b036f4cc-c7e0-11e4-8015-0c2d255dbb1a.png)


![screen shot 2015-03-11 at 11 17 59 am](https://cloud.githubusercontent.com/assets/1579786/6598169/84777faa-c7e0-11e4-9317-349a3dab9d04.png)

**Closed by damiansima** 2015-03-11 14:21 UTC

**Comment by tomwilding** [comment] 2015-03-11 23:33
Thanks @damiansima great work! Looking forward to increasing my test coverage percentage!
